#! /bin/bash -v
yum -y update

# Helper function
function error_exit
{
  /opt/aws/bin/cfn-signal -e 1 -r "$1" '[Ref:WebServerWaitHandle]'
  exit 1
}
yum -y install java-1.8.0-openjdk-devel tomcat8
yum -y remove  java-1.7.0-openjdk
chkconfig tomcat8 on
service tomat8 start

# All is well so signal success
/opt/aws/bin/cfn-signal -e $? -r "Server setup complete" '[Ref:WebServerWaitHandle]'
